# `jobs' is a required top-level dictionary
jobs:
    # named jobs 
    mountstorage:
        # tasks is specified as python import path
        task: loom.system.add_sshfs_mount
        # you can use previously defined anchors
        # to pass complicated data as arguments
        # to your tasks
        args: [*storage]
        # standard cron scheduling
        schedule: "* * * * *"
        # node targets, defined in nodes.yaml
        targets: [staging, production]
        # job description
        description: Mount storage on forge and hive
    testtask:
        # tasks don't need to be Fabric tasks
        # but can be any arbitrary importable 
        # python callable!
        task: fabric.api.run
        args: ["touch /tmp/loom_was_here"]
        schedule: "* * * * *"
        targets: *dbservers
        description: Leave our mark